name: Fedora R-devel checks

on:
  push:
    branches: [ "main", "master", "test-branch" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  _R_CHECK_INSTALL_DEPENDS_: "true"
  _R_CHECK_NO_RECOMMENDED_: "true"
  _R_CHECK_DOC_SIZES2_:  "true"
  _R_CHECK_DEPRECATED_DEFUNCT_: "true"
  _R_CHECK_NATIVE_ROUTINE_REGISTRATION_: "true"
  _R_CHECK_FF_CALLS_:    "registration"
  _R_CHECK_LIMIT_CORES_: "true"

jobs:
  #--------------------------------------------------------------------
  gcc-fedora:
    name: "Fedora 42 • R-devel • GCC 15"
    runs-on: ubuntu-latest
    container:
      image: rhub/fedora-gcc-devel:latest
      options: --user root
    env:
      _R_CHECK_SUGGESTS_ONLY_: "false"
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          dnf -y install cmake make git
          
      - name: Put /opt/R-devel/bin on PATH
        run: echo "/opt/R-devel/bin" >> "$GITHUB_PATH"

      - name: Build & check
        run: |
          R CMD build .
          PKG=$(ls -1t *.tar.gz | head -n 1)
          R CMD check --as-cran --no-stop-on-test-error "$PKG"

      - name: Upload artifacts
        if: always()                          # run even on failure
        uses: actions/upload-artifact@v4
        with:
          name: libdeflate-gcc-${{ github.run_id }}
          path: |
            *.tar.gz
            *.Rcheck/**
            */00*.out
            */00*.log
# -------------------------------------------------------------------
  clang-fedora:
    name: "Fedora 42 • R-devel • Clang 20"
    runs-on: ubuntu-latest
    container:
      image: rhub/fedora-clang-devel:latest
      options: --user root
    env:
      _R_CHECK_SUGGESTS_ONLY_: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          dnf -y install cmake make git

      - name: Put /opt/R-devel/bin on PATH
        run: echo "/opt/R-devel/bin" >> "$GITHUB_PATH"

      - name: Build & check
        run: |
          R CMD build .
          PKG=$(ls -1t *.tar.gz | head -n 1)
          R CMD check --as-cran --no-stop-on-test-error "$PKG"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: libdeflate-clang-${{ github.run_id }}
          path: |
            *.tar.gz
            *.Rcheck/**
            */00*.out
            */00*.log